theme: jekyll-theme-minimal
logo: https://sallake.github.io/denys-nevozhai-guNIjIuUcgY-unsplash.jpg
title: Salma

# Site Author
name: Sal
bio: Sydney, Australia

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
    
social-network-links:
  email: "someone@example.com"
  linkedin: sallake

